apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: netcat-listen
    app.kubernetes.io/component: netcat-listen
    app.kubernetes.io/instance: netcat-listen
    app.kubernetes.io/name: netcat-listen
    app.kubernetes.io/part-of: netcat-Server
  name: netcat-listen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcat-listen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netcat-listen
        deployment: netcat-listen
    spec:
      containers:
      - image: quay.io/jwesterl/netcat:latest
        imagePullPolicy: Always
        name: netcat-listen
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
